version: '3'

services:
  zookeeper:
    profiles: ["tests"]
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      JVMFLAGS: "-Xmx256m -Xms256m"

  kafka:
    profiles: ["tests"]
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_NETWORK_THREADS: 4
      KAFKA_NUM_IO_THREADS: 4
      KAFKA_BACKGROUND_THREADS: 4
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"

  tester:
    image: makeomatic/node:${IMAGE_TAG:-22-rdkafka-tester}
    volumes:
      - ${PWD}:/src
      - ${PWD}/ci/npmrc:/usr/local/etc/npmrc:ro
      - ${PNPM_STORE:-~/.pnpm-store}:/tmp/.pnpm-store
    command: /bin/sh -c "addgroup --gid 501 builder; useradd -g ${UID} -u ${UID} --create-home builder; exec tail -f /dev/null"
    network_mode: host
    env_file:
      - .env
    environment:
      - UV_THREADPOOL_SIZE=16
      - CI=true
      - UID=${UID:-1000}
